softwood:
  base:
  - '44031100'
  - '44032101'
  - '44032201'
  - '44032301'
  - '44032401'
  - '44032501'
  - '44032601'
  - '44039901'
  - '44061100'
  - '44069100'
  - '44071100'
  - '44071200'
  - '44071300'
  - '44071400'
  - '44071900'
  rates:
    default: 0.1
  usmca_exempt: 0
upholstered_wooden_furniture:
  base:
  - '9401614011'
  - '9401614031'
  - '9401616011'
  - '9401616031'
  rates:
    default: 0.25
    '5880': 0.15
    '4120': 0.1
    '4330': 0.15
    '4231': 0.15
    '4870': 0.15
    '4791': 0.15
    '4910': 0.15
    '4351': 0.15
    '4099': 0.15
    '4470': 0.15
    '4050': 0.15
    '4279': 0.15
    '4280': 0.15
    '4840': 0.15
    '4370': 0.15
    '4190': 0.15
    '4759': 0.15
    '4490': 0.15
    '4510': 0.15
    '4239': 0.15
    '4730': 0.15
    '4210': 0.15
    '4550': 0.15
    '4710': 0.15
    '4850': 0.15
    '4359': 0.15
    '4792': 0.15
    '4700': 0.15
    '4010': 0.15
  usmca_exempt: 0
kitchen_cabinets_and_parts:
  base:
  - '9403409060'
  - '9403608093'
  - '9403910080'
  rates:
    default: 0.25
    '5880': 0.15
    '4120': 0.1
    '4330': 0.15
    '4231': 0.15
    '4870': 0.15
    '4791': 0.15
    '4910': 0.15
    '4351': 0.15
    '4099': 0.15
    '4470': 0.15
    '4050': 0.15
    '4279': 0.15
    '4280': 0.15
    '4840': 0.15
    '4370': 0.15
    '4190': 0.15
    '4759': 0.15
    '4490': 0.15
    '4510': 0.15
    '4239': 0.15
    '4730': 0.15
    '4210': 0.15
    '4550': 0.15
    '4710': 0.15
    '4850': 0.15
    '4359': 0.15
    '4792': 0.15
    '4700': 0.15
    '4010': 0.15
  usmca_exempt: 0
vehicles_completed_mhd:
  base:
  - '87012100'
  - '87012200'
  - '87012300'
  - '87012400'
  - '87012900'
  - '87041010'
  - '87041050'
  - '87042211'
  - '87042251'
  - '87042301'
  - '87043201'
  - '87044200'
  - '87044300'
  - '87045200'
  - '87046000'
  - '87049001'
  - '87054000'
  - '8705900080'
  - '87060003'
  - '8706000520'
  - '8706000575'
  - '87060025'
  - '87060050'
  - '87091100'
  - '87091900'
  rates:
    default: 0.25
  usmca_exempt: 1
buses_heading_8702:
  base:
  - '87021031'
  - '87021061'
  - '87022031'
  - '87022061'
  - '87023031'
  - '87023061'
  - '87024031'
  - '87024061'
  - '87029031'
  - '87029061'
  rates:
    default: 0.1
  usmca_exempt: 0
vehicle_parts_mhd:
  base:
  - '4009120020'
  - '4009220020'
  - '4009320020'
  - '4009420020'
  - '40111050'
  - '4011201015'
  - '4011201025'
  - '4011201035'
  - '40121940'
  - '40121980'
  - '40122060'
  - '40131000'
  - '4016996010'
  - '7007211110'
  - '70072151'
  - '70091000'
  - '73201030'
  - '73201060'
  - '73201090'
  - '73202010'
  - '83012000'
  - '83021030'
  - '83023030'
  - '83023060'
  - '84073414'
  - '84073418'
  - '84073425'
  - '84073444'
  - '84073448'
  - '84073455'
  - '84082020'
  - '8409911040'
  - '8409991040'
  - '84133010'
  - '84133090'
  - '84139110'
  - '8413919010'
  - '8414308030'
  - '84145930'
  - '8414596540'
  - '84148005'
  - '84152000'
  - '84212300'
  - '84213200'
  - '84254900'
  - '84269100'
  - '8431100090'
  - '84821010'
  - '8482105044'
  - '8482105048'
  - '8482200020'
  - '8482200030'
  - '8482200040'
  - '8482200061'
  - '8482200070'
  - '8482200081'
  - '84824000'
  - '84825000'
  - '84831010'
  - '85013220'
  - '8501325540'
  - '85013261'
  - '8501332080'
  - '85013330'
  - '85013340'
  - '85013361'
  - '85013430'
  - '85013461'
  - '85014020'
  - '85014040'
  - '85014050'
  - '85014060'
  - '85015120'
  - '85015140'
  - '85015150'
  - '85015160'
  - '85015240'
  - '8501528040'
  - '85071000'
  - '85079040'
  - '85111000'
  - '85112000'
  - '85113000'
  - '85114000'
  - '85115000'
  - '85118020'
  - '85118060'
  - '85119060'
  - '85122020'
  - '85122040'
  - '85123000'
  - '85124020'
  - '85124040'
  - '85129020'
  - '85129060'
  - '85129070'
  - '85198120'
  - '8525601010'
  - '85272115'
  - '85272125'
  - '85272140'
  - '85272940'
  - '85272980'
  - '8536410005'
  - '8539100010'
  - '8539100050'
  - '85443000'
  - '87060003'
  - '87060005'
  - '87060015'
  - '87060025'
  - '8707905020'
  - '8707905060'
  - '8707905080'
  - '8707905090'
  - '87081030'
  - '87081060'
  - '87082100'
  - '87082200'
  - '87082915'
  - '87082925'
  - '87082951'
  - '8708301010'
  - '87083050'
  - '87084011'
  - '87084030'
  - '87084050'
  - '87084060'
  - '87084065'
  - '87084070'
  - '87084075'
  - '87085031'
  - '87085061'
  - '87085065'
  - '87085075'
  - '87085081'
  - '87085085'
  - '87085089'
  - '87085091'
  - '87085093'
  - '87085095'
  - '87085099'
  - '87087005'
  - '87087025'
  - '87087035'
  - '87087045'
  - '87087060'
  - '87088013'
  - '87088016'
  - '87088055'
  - '87088060'
  - '87088065'
  - '87089150'
  - '87089165'
  - '87089170'
  - '87089175'
  - '87089265'
  - '87089360'
  - '87089375'
  - '87089410'
  - '87089450'
  - '87089465'
  - '87089470'
  - '87089475'
  - '87089505'
  - '87089515'
  - '87089520'
  - '87089903'
  - '87089906'
  - '87089923'
  - '87089927'
  - '87089931'
  - '87089941'
  - '8708994850'
  - '87089953'
  - '87089955'
  - '87089958'
  - '87089968'
  - '87099000'
  - '90291080'
  - '9029204080'
  - '94012000'
  rates:
    default: 0.25
  usmca_exempt: 1
steel:
  base:
  - '73012010'
  - '73012050'
  - '73023000'
  - '73072110'
  - '73072150'
  - '73072210'
  - '73072250'
  - '73072300'
  - '73072900'
  - '73079110'
  - '73079130'
  - '73079150'
  - '73079230'
  - '73079290'
  - '73079330'
  - '73079360'
  - '73079390'
  - '73079910'
  - '73079930'
  - '73079950'
  - '73081000'
  - '73082000'
  - '73083010'
  - '73083050'
  - '73084000'
  - '73089030'
  - '73089060'
  - '73089070'
  - '73089095'
  - '73090000'
  - '73101000'
  - '73102100'
  - '73102900'
  - '73110000'
  - '73121005'
  - '73121010'
  - '73121020'
  - '73121030'
  - '73121050'
  - '73121060'
  - '73121070'
  - '73121080'
  - '73121090'
  - '73129000'
  - '73130000'
  - '73141210'
  - '73141220'
  - '73141230'
  - '73141260'
  - '73141290'
  - '73141410'
  - '73141420'
  - '73141430'
  - '73141460'
  - '73141490'
  - '73141901'
  - '73142000'
  - '73143110'
  - '73143150'
  - '73143900'
  - '73144100'
  - '73144200'
  - '73144930'
  - '73144960'
  - '73145000'
  - '73151100'
  - '73151200'
  - '73151900'
  - '73152010'
  - '73152050'
  - '73158100'
  - '73158210'
  - '73158230'
  - '73158250'
  - '73158270'
  - '73158910'
  - '73158930'
  - '73158950'
  - '73159000'
  - '73160000'
  - '73170010'
  - '73170020'
  - '73170030'
  - '73170055'
  - '73170065'
  - '73170075'
  - '73181100'
  - '73181200'
  - '73181300'
  - '73181410'
  - '73181450'
  - '73181520'
  - '73181540'
  - '73181550'
  - '73181560'
  - '73181580'
  - '73181600'
  - '73181900'
  - '73182100'
  - '73182200'
  - '73182300'
  - '73182400'
  - '73182900'
  - '73194020'
  - '73194030'
  - '73194050'
  - '73199010'
  - '73199090'
  - '73201030'
  - '73201060'
  - '73201090'
  - '73202010'
  - '73202050'
  - '73209010'
  - '73209050'
  - '73211110'
  - '73211130'
  - '73211160'
  - '73211200'
  - '73211900'
  - '73218110'
  - '73218150'
  - '73218210'
  - '73218250'
  - '73218900'
  - '73219010'
  - '73219020'
  - '73219040'
  - '73219050'
  - '73219060'
  - '73221900'
  - '73229000'
  - '73231000'
  - '73239300'
  - '73239400'
  - '73239910'
  - '73239930'
  - '73239950'
  - '73239970'
  - '73239990'
  - '73241000'
  - '73242900'
  - '73249000'
  - '73259100'
  - '73259910'
  - '73259950'
  - '73261100'
  - '73261900'
  - '73262000'
  - '73269010'
  - '73269025'
  - '73269035'
  - '73269045'
  - '73269060'
  - '73269086'
  - '84313100'
  - '84314200'
  - '84314910'
  - '84314990'
  - '84321000'
  - '84329000'
  - '85479000'
  - '94032000'
  - '94059920'
  - '94059940'
  - '94062000'
  - '94069001'
  rates:
    default: 0.5
    '4120': 0.25
  usmca_exempt: 0
aluminum_base_articles:
  base:
  - '760110'
  - '760120'
  - '760410'
  - '760421'
  - '760429'
  - '760511'
  - '760519'
  - '760521'
  - '760529'
  - '760611'
  - '760612'
  - '760691'
  - '760692'
  - '760711'
  - '760719'
  - '760720'
  - '760810'
  - '760820'
  - '760900'
  - '76169951'
  rates:
    default: 0.5
    '4120': 0.25
  usmca_exempt: 0
aluminum_derivative_9903_85_04:
  base:
  - '76141050'
  - '76149020'
  - '76149040'
  - '76149050'
  - '87081030'
  - '87082921'
  rates:
    default: 0.5
    '4120': 0.25
  usmca_exempt: 0
aluminum_derivative_9903_85_07:
  base:
  - '76101000'
  - '76109000'
  - '7615102015'
  - '7615102025'
  - '7615103015'
  - '7615103025'
  - '7615105020'
  - '7615105040'
  - '7615107125'
  - '7615107130'
  - '7615107155'
  - '7615107180'
  - '7615109100'
  - '7615200000'
  - '7616109090'
  - '7616991000'
  - '7616995130'
  - '7616995140'
  - '7616995190'
  rates:
    default: 0.5
    '4120': 0.25
  usmca_exempt: 0
aluminum_derivative_9903_85_08:
  base:
  - '6603908100'
  - '8302103000'
  - '8302106030'
  - '8302106060'
  - '8302106090'
  - '8302200000'
  - '8302303010'
  - '8302303060'
  - '8302413000'
  - '8302416015'
  - '8302416045'
  - '8302416050'
  - '8302416080'
  - '8302423010'
  - '8302423015'
  - '8302423065'
  - '8302496035'
  - '8302496045'
  - '8302496055'
  - '8302496085'
  - '8302500000'
  - '8302603000'
  - '8302609000'
  - '8305100050'
  - '8306300000'
  - '8414596590'
  - '8415908025'
  - '8415908045'
  - '8415908085'
  - '8418998005'
  - '8418998050'
  - '8418998060'
  - '8419505000'
  - '8419901000'
  - '8422900640'
  - '8424909080'
  - '8473302000'
  - '8473305100'
  - '8479899599'
  - '8479908500'
  - '8479909596'
  - '8481909060'
  - '8481909085'
  - '8486900000'
  - '8487900080'
  - '8503009520'
  - '8508700000'
  - '8513902000'
  - '8515902000'
  - '8516905000'
  - '8516908050'
  - '8517710000'
  - '8517790000'
  - '8529907300'
  - '8529909760'
  - '8536908585'
  - '8538100000'
  - '8541900000'
  - '8543908885'
  - '8547900020'
  - '8547900030'
  - '8547900040'
  - '8708103050'
  - '87081060'
  - '8708295160'
  - '8708806590'
  - '8708996890'
  - '8716805010'
  - '8807300060'
  - '9013908000'
  - '9031909195'
  - '9401999081'
  - '94031000'
  - '94032000'
  - '9403991040'
  - '9403999010'
  - '9403999015'
  - '9403999020'
  - '9403999040'
  - '9403999045'
  - '9405994020'
  - '9506114080'
  - '9506514000'
  - '9506516000'
  - '9506594040'
  - '9506702090'
  - '9506910010'
  - '9506910020'
  - '9506910030'
  - '9506990510'
  - '9506990520'
  - '9506990530'
  - '9506991500'
  - '9506992000'
  - '9506992580'
  - '9506992800'
  - '9506995500'
  - '9506996080'
  - '9507302000'
  - '9507304000'
  - '9507306000'
  - '9507308000'
  - '9507906000'
  - '9603908050'
  rates:
    default: 0.5
    '4120': 0.25
  usmca_exempt: 0
copper_derivatives:
  base:
  - '74061000'
  - '74062000'
  - '74071015'
  - '74071030'
  - '74071050'
  - '74072115'
  - '74072130'
  - '74072150'
  - '74072170'
  - '74072190'
  - '74072916'
  - '74072934'
  - '74072938'
  - '74072940'
  - '74072950'
  - '74081130'
  - '74081160'
  - '74081900'
  - '74082100'
  - '74082210'
  - '74082250'
  - '74082910'
  - '74082950'
  - '74091110'
  - '74091150'
  - '74091910'
  - '74091950'
  - '74091990'
  - '74092100'
  - '74092900'
  - '74093110'
  - '74093150'
  - '74093190'
  - '74093910'
  - '74093950'
  - '74093990'
  - '74094000'
  - '74099010'
  - '74099050'
  - '74099090'
  - '74101100'
  - '74101200'
  - '74102130'
  - '74102160'
  - '74102200'
  - '74111010'
  - '74111050'
  - '74112110'
  - '74112150'
  - '74112200'
  - '74112910'
  - '74112950'
  - '74121000'
  - '74122000'
  - '74130010'
  - '74130050'
  - '74130090'
  - '74151000'
  - '74152100'
  - '74152900'
  - '74153305'
  - '74153310'
  - '74153380'
  - '74153900'
  - '74181000'
  - '74182010'
  - '74182050'
  - '74192000'
  - '74198003'
  - '74198006'
  - '74198009'
  - '74198015'
  - '74198016'
  - '74198017'
  - '74198030'
  - '74198050'
  - '85444210'
  - '85444220'
  - '85444290'
  - '85444910'
  rates:
    default: 0.5
  usmca_exempt: 0
automobiles_passenger_and_light_trucks:
  base:
  - '87032201'
  - '87032301'
  - '87032401'
  - '87033101'
  - '87033201'
  - '87033301'
  - '87034000'
  - '87035000'
  - '87036000'
  - '87037000'
  - '87038000'
  - '87039001'
  - '87042101'
  - '87043101'
  - '87044100'
  - '87045100'
  rates:
    default: 0.25
  usmca_exempt: 1
automobile_parts:
  base:
  - '4009120020'
  - '4009220020'
  - '4009320020'
  - '4009420020'
  - '40111010'
  - '40111050'
  - '40112010'
  - '40121940'
  - '40121980'
  - '40122060'
  - '4013100010'
  - '4013100020'
  - '4016996010'
  - '70072151'
  - '70091000'
  - '732010'
  - '73202010'
  - '83012000'
  - '83021030'
  - '830230'
  - '84073100'
  - '840732'
  - '840733'
  - '840734'
  - '84082020'
  - '8409911040'
  - '8409991040'
  - '84133010'
  - '84133090'
  - '84139110'
  - '8413919010'
  - '8414308030'
  - '84145930'
  - '8414596540'
  - '84148005'
  - '84152000'
  - '84212300'
  - '84213200'
  - '84254900'
  - '84269100'
  - '8431100090'
  - '8471'
  - '84821010'
  - '8482105044'
  - '8482105048'
  - '8482200020'
  - '8482200030'
  - '8482200040'
  - '8482200061'
  - '8482200070'
  - '8482200081'
  - '84824000'
  - '84825000'
  - '8483101030'
  - '850132'
  - '850133'
  - '850134'
  - '850140'
  - '850151'
  - '850152'
  - '850710'
  - '850760'
  - '85079040'
  - '85079080'
  - '8511100000'
  - '85112000'
  - '8511300040'
  - '8511300080'
  - '85114000'
  - '85115000'
  - '85118020'
  - '85118060'
  - '8511906020'
  - '8511906040'
  - '85122020'
  - '85122040'
  - '85123000'
  - '85124020'
  - '85124040'
  - '85129020'
  - '85129060'
  - '85129070'
  - '85198120'
  - '8525601010'
  - '852721'
  - '852729'
  - '8536410005'
  - '853710'
  - '853720'
  - '8539100010'
  - '8539100050'
  - '85443000'
  - '87060003'
  - '87060005'
  - '87060015'
  - '87060025'
  - '8707'
  - '8707100020'
  - '8707100040'
  - '8707905020'
  - '8707905040'
  - '8707905060'
  - '8707905080'
  - '87081030'
  - '87081060'
  - '87082100'
  - '870822'
  - '870829'
  - '870830'
  - '87084011'
  - '87084070'
  - '87084075'
  - '870850'
  - '870870'
  - '870880'
  - '870891'
  - '87089360'
  - '87089375'
  - '870894'
  - '870895'
  - '87089903'
  - '87089906'
  - '87089923'
  - '87089927'
  - '87089931'
  - '87089941'
  - '8708994850'
  - '87089953'
  - '87089955'
  - '87089958'
  - '87089968'
  - '87169050'
  - '901510'
  - '902910'
  - '9029204080'
  - '94012000'
  rates:
    default: 0.25
  usmca_exempt: 1
