headline_rates:
  default: 0.0
  '1220': 0.35
  '2010': 0.25
  '5700': 0.1
product_rates: {}
product_country_rates:
- country: '2010'
  name: potash_mx
  rate: 0.1
  hts:
  - '2815200050'
  - '2815200090'
  - '3104200010'
  - '3104200050'
  - '3104300000'
  - '3104900100'
  - '3105100000'
  - '3105200000'
  - '3105600000'
- country: '1220'
  name: potash_ca
  rate: 0.1
  hts:
  - '2815200050'
  - '2815200090'
  - '3104200010'
  - '3104200050'
  - '3104300000'
  - '3104900100'
  - '3105100000'
  - '3105200000'
  - '3105600000'
- country: '1220'
  name: energy_ca
  rate: 0.1
  hts:
  - '2504105000'
  - '2504900000'
  - '2511105000'
  - '2529210000'
  - '2529220000'
  - '2530901000'
  - '2602000040'
  - '2602000060'
  - '2603000030'
  - '2604000040'
  - '2605000000'
  - '2606000030'
  - '2606000060'
  - '2606000090'
  - '2607000030'
  - '2608000030'
  - '2609000000'
  - '2610000020'
  - '2610000040'
  - '2610000060'
  - '2611003000'
  - '2611006000'
  - '2612100000'
  - '2612200000'
  - '2614003000'
  - '2614006020'
  - '2614006040'
  - '2615100000'
  - '2615903000'
  - '2615906030'
  - '2615906060'
  - '2615906090'
  - '2616100030'
  - '2616900030'
  - '2617100000'
  - '2617900030'
  - '2620110000'
  - '2620193000'
  - '2620196030'
  - '2620210030'
  - '2620300030'
  - '2620400030'
  - '2620910000'
  - '2620991000'
  - '2620992000'
  - '2620993000'
  - '2620997520'
  - '2701110000'
  - '2701120010'
  - '2701120050'
  - '2701190010'
  - '2701190050'
  - '2707100000'
  - '2707200000'
  - '2707300010'
  - '2707300020'
  - '2707300030'
  - '2707300040'
  - '2707400000'
  - '2707500000'
  - '2707910000'
  - '2707991000'
  - '2707992000'
  - '2707994000'
  - '2707995100'
  - '2707995500'
  - '2707995900'
  - '2707999010'
  - '2707999090'
  - '2709001000'
  - '2709002010'
  - '2709002090'
  - '2710121510'
  - '2710121514'
  - '2710121519'
  - '2710121520'
  - '2710121550'
  - '2710121805'
  - '2710121890'
  - '2710122500'
  - '2710124545'
  - '2710124560'
  - '2710124595'
  - '2710129000'
  - '2710190605'
  - '2710190615'
  - '2710190625'
  - '2710190630'
  - '2710190635'
  - '2710190650'
  - '2710191102'
  - '2710191103'
  - '2710191104'
  - '2710191105'
  - '2710191107'
  - '2710191108'
  - '2710191111'
  - '2710191113'
  - '2710191114'
  - '2710191115'
  - '2710191125'
  - '2710191150'
  - '2710191600'
  - '2710192400'
  - '2710192500'
  - '2710192600'
  - '2710193010'
  - '2710193020'
  - '2710193030'
  - '2710193040'
  - '2710193050'
  - '2710193070'
  - '2710193080'
  - '2710193500'
  - '2710194000'
  - '2710194530'
  - '2710194540'
  - '2710194545'
  - '2710194590'
  - '2710199000'
  - '2710200510'
  - '2710200520'
  - '2710200550'
  - '2710201002'
  - '2710201003'
  - '2710201004'
  - '2710201005'
  - '2710201007'
  - '2710201008'
  - '2710201011'
  - '2710201013'
  - '2710201014'
  - '2710201015'
  - '2710201025'
  - '2710201050'
  - '2710201500'
  - '2710202500'
  - '2710910010'
  - '2710910050'
  - '2710990500'
  - '2710991000'
  - '2710991600'
  - '2710992100'
  - '2710993100'
  - '2710993200'
  - '2710993900'
  - '2710994500'
  - '2710999000'
  - '2711110000'
  - '2711120010'
  - '2711120020'
  - '2711130010'
  - '2711130020'
  - '2711140010'
  - '2711140020'
  - '2711140030'
  - '2711140040'
  - '2711190010'
  - '2711190020'
  - '2711210000'
  - '2711290010'
  - '2711290015'
  - '2711290020'
  - '2711290025'
  - '2711290060'
  - '2804500020'
  - '2804800000'
  - '2805199010'
  - '2805300005'
  - '2805300010'
  - '2805300015'
  - '2805300020'
  - '2805300050'
  - '2805300090'
  - '2811110000'
  - '2811191000'
  - '2811291000'
  - '2813901000'
  - '2817000000'
  - '2818200000'
  - '2818300000'
  - '2819100000'
  - '2819900000'
  - '2820100000'
  - '2820900000'
  - '2822000010'
  - '2822000090'
  - '2823000000'
  - '2825200000'
  - '2825300010'
  - '2825300050'
  - '2825400000'
  - '2825600000'
  - '2825800000'
  - '2825901000'
  - '2825901500'
  - '2825902000'
  - '2825903000'
  - '2826120000'
  - '2826300000'
  - '2826909010'
  - '2827350000'
  - '2827391000'
  - '2827392500'
  - '2827394000'
  - '2827396000'
  - '2827396500'
  - '2827491000'
  - '2830901000'
  - '2830901500'
  - '2833240000'
  - '2833270000'
  - '2833291000'
  - '2833293000'
  - '2833294000'
  - '2833294500'
  - '2833295110'
  - '2834290500'
  - '2836910010'
  - '2836910050'
  - '2836991000'
  - '2836992000'
  - '2841300000'
  - '2841501000'
  - '2841610000'
  - '2841690010'
  - '2841690090'
  - '2841800010'
  - '2841800020'
  - '2841800050'
  - '2841901000'
  - '2841903000'
  - '2844101000'
  - '2844102010'
  - '2844102025'
  - '2844420000'
  - '2844430021'
  - '2846100010'
  - '2846100050'
  - '2846902005'
  - '2846902015'
  - '2846902040'
  - '2846902082'
  - '2846902084'
  - '2846904000'
  - '2846908070'
  - '2846908075'
  - '2846908090'
  - '2849902000'
  - '2849903000'
  - '2850001000'
  - '2850002000'
  - '2853909010'
  - '2915293000'
  - '3206200030'
  - '3206420000'
  - '3606903000'
  - '3801101000'
  - '3801105010'
  - '3801105090'
  - '3801200000'
  - '3801300000'
  - '3801900000'
  - '3815110000'
  - '3818000010'
  - '3824993100'
  - '3824993500'
  - '3824993600'
  - '3826001000'
  - '3826003000'
  - '6815110000'
  - '6815120000'
  - '6815130000'
  - '6815190000'
  - '7110110010'
  - '7110110020'
  - '7110110050'
  - '7110190000'
  - '7110210000'
  - '7110290000'
  - '7110310000'
  - '7110390000'
  - '7110410010'
  - '7110410030'
  - '7110410050'
  - '7110490010'
  - '7110490050'
  - '7112920100'
  - '7115100000'
  - '7115906000'
  - '7118900020'
  - '7202111000'
  - '7202115000'
  - '7202191000'
  - '7202195000'
  - '7202300000'
  - '7202410000'
  - '7202491000'
  - '7202495010'
  - '7202495090'
  - '7202500000'
  - '7202600000'
  - '7202800000'
  - '7202910000'
  - '7202920000'
  - '7202934000'
  - '7202938000'
  - '7202991000'
  - '7204210000'
  - '7204410020'
  - '7204410040'
  - '7204410060'
  - '7204410080'
  - '7204490020'
  - '7204490040'
  - '7204490060'
  - '7204490070'
  - '7205100000'
  - '7205290000'
  - '7405006030'
  - '7409901030'
  - '7409905030'
  - '7409909030'
  - '7501100000'
  - '7501200000'
  - '7502100000'
  - '7502200000'
  - '7503000000'
  - '7504000010'
  - '7504000050'
  - '7614101000'
  - '7614105000'
  - '7614904000'
  - '7614905000'
  - '7801910000'
  - '7901110000'
  - '7901121000'
  - '7901125000'
  - '7901200000'
  - '7902000000'
  - '7903100000'
  - '7903903000'
  - '7903906000'
  - '8001100000'
  - '8001200010'
  - '8001200050'
  - '8001200090'
  - '8007003200'
  - '8101100000'
  - '8101940000'
  - '8101970000'
  - '8101991000'
  - '8103200030'
  - '8103200090'
  - '8103300000'
  - '8103910000'
  - '8103990000'
  - '8104110000'
  - '8104190000'
  - '8104200000'
  - '8104300000'
  - '8104900000'
  - '8105203000'
  - '8105206000'
  - '8105209000'
  - '8105300000'
  - '8105900000'
  - '8106100000'
  - '8106900000'
  - '8108200010'
  - '8108200015'
  - '8108200030'
  - '8108200095'
  - '8108300000'
  - '8108903030'
  - '8108903060'
  - '8108906020'
  - '8108906031'
  - '8108906045'
  - '8108906060'
  - '8108906075'
  - '8110100000'
  - '8110200000'
  - '8110900000'
  - '8111003000'
  - '8111004700'
  - '8111004910'
  - '8111004990'
  - '8111006000'
  - '8112120000'
  - '8112130000'
  - '8112190000'
  - '8112210000'
  - '8112220000'
  - '8112290000'
  - '8112310000'
  - '8112390000'
  - '8112920700'
  - '8112921000'
  - '8112923000'
  - '8112924000'
  - '8112926000'
  - '8112926500'
  - '8112927000'
  - '8112991000'
  - '8112992000'
  - '8505110050'
  - '8505110070'
  - '8545110010'
  - '8545110020'
  - '8545110050'
  - '8545200000'
  - '8545904000'
